### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fritx** [fritx/win-sqlcipher#1]
- [x] target build args f0a9aa1d04bf33fb17ae0a58a6f8af5a99cebf09
- [x] nw test
- [x] electron test
- [ ] dist-url??? https://github.com/fritx/unix-sqlcipher/issues/4#issuecomment-379299122
- [x] dont throw error, echo instead
- [ ] tool: nw-auto-rebuild
- [x] openssl_dir (win32/win64) conditions in sqlite3.gyp https://github.com/liubiggun/node-sqlite3/pull/2
- [ ] libeay32.dll ssleay32.dll (win32/win64) included in sources or ensure env.PATH

cc @liubiggun https://github.com/liubiggun/node-sqlite3
